name: easy_chat_game
description: To implement a scripted chat game for fun
version: 1.1.2
homepage: https://github.com/nooralibutt/easy_chat_game
repository: https://github.com/nooralibutt/easy_chat_game

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  simple_animations: ^5.0.0+3
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.18
  confetti: ^0.7.0
  just_audio: ^0.9.31
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  assets:
  - lib/assets/
  - lib/assets/audio/
  - lib/assets/audio/applause.mp3
  - lib/assets/chat/