name: easy_chat_game
description: A new Flutter project.
version: 1.0.0
homepage: https://github.com/nooralibutt/easy_chat_game
repository: https://github.com/nooralibutt/easy_chat_game

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  simple_animations: ^4.0.1
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.17
  confetti: ^0.7.0
  audioplayers: ^0.20.1
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  assets:
    - assets/
    - assets/chat/